export const EMPTY_STRING = "";
export const ZERO = 0;
export const ONE = 1;
export const SEVEN = 7;
export const FOUR_ZERO_ONE = 401;
export const MOVIE_ID = "movieTitle";
export const HOME_PAGE = "/";
export const TO_LOGIN_PAGE = "/login";
export const TO_ADD_MOVIE_PAGE = "/addMovie";
export const EQUALS_TO = "=";
export const BY_SEMI_COLON = ";";
export const BY_COMMA_AND_SPACE = ", ";
